### ISSUE TITLE
Enterprise Support and Data Clarification

### ISSUE THREAD

**Issue by jeffschaper** [maael/template-repository-usage-action#486]
Hi @maael 👋 

I've been investigating your project and it appears to fit my use case, but I have a couple questions that weren't obvious to me when reading through the documentation. Can you help me understand more about your project?

1. Would I be able to utilize the action in a GitHub enterprise server environment?
2. I'm a little confused about [line 7](https://github.com/maael/template-repository-usage-action/blob/a16e1cc91bbe81e592c02a86f982e3cf7e24b616/README.md?plain=1#L7) in the README. Does this mean the action will only collect repos generated from a template within a specific org. For example, repos within the `maael` org. Or would it also collect repos generated from a template across multiple orgs? For example, if I were to use this template and generate a new repo in my `jeffschaper` org, would my new repo show up here in the README?

Thanks for helping me understand and contributing to open source!

**Comment by maael** [comment]
👋 Hey there.

> 1. Would I be able to utilize the action in a GitHub enterprise server environment?

The repository license should clarify this, [which you can find here](https://github.com/maael/template-repository-usage-action?tab=MIT-1-ov-file#readme), it's the standard MIT license. TL;DR - basically, you can do whatever you want as long as you include the original copyright and license notice in any copy of the software/source. The software is provided "as is", there is no "Enterprise support" offered.

> 2. ...

The org is passed in for this GraphQL query to the GitHub API:
```gql
query orgRepos($owner: String!, $afterCursor: String) {
  repositoryOwner(login: $owner) {
    repositories(first: 100, after:$afterCursor, orderBy:{field:CREATED_AT, direction:DESC}) {
      ...
    }
  }
}
```
where `$owner` is the `org` option provided, or the org of the repository that this action (the template usage) is being run in.

So it will collect from a single org.

Hopefully that answers your questions, if not, let me know.

**Comment by jeffschaper** [comment]
Thank you for answering my questions @maael! I'll go ahead and close this issue.
